name: test-gcp-credentials

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: GitHub-Actions-CICD
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: info
