  
name: Test Deployment

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Test deployment
      run: |
        DEPLOY_URL=$(gcloud run services list --platform managed | grep ${{ env.APPLICATION_NAME }}  | awk '{print $4}')
        curl -sL --max-time 3 -o /dev/null -w "%{http_code}" $DEPLOY_URL | grep 200 || exit 1
