  
name: Test Deployment

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud info
        
    - name: Deploy to Cloud Run
      run: gcloud run deploy ${{ env.APPLICATION_NAME }} --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest --platform=managed --allow-unauthenticated

    - name: Test deployment
      run: |
        DEPLOY_URL=$(gcloud run services list --platform managed | grep ${{ env.APPLICATION_NAME }}  | awk '{print $4}')
        curl -sL --max-time 3 -o /dev/null -w "%{http_code}" $DEPLOY_URL | grep 200 || exit 1
